theme: jekyll-theme-midnight
title: 21' Summer 💙 Paper Virtual Meetup
description: We meet weekly to discuss papers about distributed systems
google_analytics: UA-83991908-1
github:
  is_project_page: false